services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-frontend-dev
