services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend
      args:
        - BACKEND_URL=http://localhost:8080/api
  server:
    image: todo-backend
    build:
      context: ./todo-backend
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:5.0.6
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
  redis:
    image: redis:6.2.6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server
